# Generated by Django 4.2.9 on 2026-03-14 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionDocumento',
            fields=[
                ('idClasificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreClasificacion', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Clasificación',
                'verbose_name_plural': 'Clasificaciones',
                'db_table': 'clasificacion_documento',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('idDocumento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaCarga', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('revision', 'En revisión'), ('archivado', 'Archivado')], default='activo', max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documento',
                'ordering': ['-fechaCarga'],
            },
        ),
        migrations.CreateModel(
            name='HistorialDocumento',
            fields=[
                ('idHistorial', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=100)),
                ('fechaAccion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historial de Documentos',
                'db_table': 'historial_documento',
                'ordering': ['-fechaAccion'],
            },
        ),
        migrations.CreateModel(
            name='RevisionDocumento',
            fields=[
                ('idRevision', models.AutoField(primary_key=True, serialize=False)),
                ('fechaRevision', models.DateField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('idDocumento', models.ForeignKey(db_column='idDocumento', on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='documentos.documento')),
            ],
            options={
                'verbose_name': 'Revisión',
                'verbose_name_plural': 'Revisiones',
                'db_table': 'revision_documento',
                'ordering': ['-fechaRevision'],
            },
        ),
    ]
