# Generated by Django 4.2.9 on 2026-03-14 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisiondocumento',
            name='idUsuario',
            field=models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.RESTRICT, related_name='revisiones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialdocumento',
            name='idDocumento',
            field=models.ForeignKey(db_column='idDocumento', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='documentos.documento'),
        ),
        migrations.AddField(
            model_name='historialdocumento',
            name='idUsuario',
            field=models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.RESTRICT, related_name='historial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='idClasificacion',
            field=models.ForeignKey(db_column='idClasificacion', on_delete=django.db.models.deletion.RESTRICT, related_name='documentos', to='documentos.clasificaciondocumento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='idUsuario',
            field=models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.RESTRICT, related_name='documentos', to=settings.AUTH_USER_MODEL),
        ),
    ]
